#include "unity.h"

#include "bit.h"

void setUp() {}
void tearDown() {}

void test_bit_mask_32_bit_common_cases(void) {
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(1), 0x01);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(2), 0x03);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(3), 0x07);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(4), 0x0F);

  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(5), 0x1F);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(6), 0x3F);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(7), 0x7F);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(8), 0xFF);

  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(16), 0xFFFF);
  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(24), 0xFFFFFF);

  TEST_ASSERT_EQUAL_UINT32(BIT_MASK(31), 0x7FFFFFFF);

  // NOTE, Causes -Wshift-count-overflow compile time error
  // NOTE, Run this with BIT_MASK64
  // TEST_ASSERT_EQUAL_UINT32(BIT_MASK(32), 0xFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT32(~0, 0xFFFFFFFF);
}

void test_bit_mask_64_bit_common_cases(void) {
  TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(32), (uint64_t)0xFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(40), (uint64_t)0xFFFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(48), (uint64_t)0xFFFFFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(56), (uint64_t)0xFFFFFFFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(63), (uint64_t)0x7FFFFFFFFFFFFFFF);

  // NOTE, Causes -Wshift-count-overflow compile time error
  // TEST_ASSERT_EQUAL_UINT64(BIT_MASK64(64), (uint64_t)0x7FFFFFFFFFFFFFFF);
  TEST_ASSERT_EQUAL_UINT64((uint64_t)~0, (uint64_t)0xFFFFFFFFFFFFFFFF);
}

int main() {
  UNITY_BEGIN();
  RUN_TEST(test_bit_mask_32_bit_common_cases);
  RUN_TEST(test_bit_mask_64_bit_common_cases);
  return UNITY_END();
}
