.TH "C/test Directory Reference" 3 "Mon Aug 3 2020" "Bit Manipulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C/test Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbit_mask_test\&.c\fP"
.br
.ti -1c
.RI "file \fBbit_reset_test\&.c\fP"
.br
.ti -1c
.RI "file \fBbit_set_test\&.c\fP"
.br
.in -1c
