.TH "C/test/bit_mask_test.c" 3 "Mon Aug 3 2020" "Bit Manipulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C/test/bit_mask_test.c
.SH SYNOPSIS
.br
.PP
\fC#include 'unity\&.h'\fP
.br
\fC#include 'bit\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP ()"
.br
.ti -1c
.RI "void \fBtearDown\fP ()"
.br
.ti -1c
.RI "void \fBtest_bit_mask_32_bit_common_cases\fP (void)"
.br
.ti -1c
.RI "void \fBtest_bit_mask_64_bit_common_cases\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "void setUp ()"

.SS "void tearDown ()"

.SS "void test_bit_mask_32_bit_common_cases (void)"

.SS "void test_bit_mask_64_bit_common_cases (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Bit Manipulation from the source code\&.
