name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: System Packages
      run: |
        sudo apt-get install ninja-build gcovr doxygen

    - name: System Information
      run: |
        cmake --version
        ninja --version
        python --version
        pip --version

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/C
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/C
      shell: bash
      run: cmake --build build --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/C/build
      shell: bash
      run: |
        ctest -C $BUILD_TYPE --output-on-failure

    # NOTE, This should only be done on commit to master
    - name: Code Coverage
      working-directory: ${{github.workspace}}/C
      shell: bash
      run: cmake --build build --target coverage

    # NOTE, This should only be done on commit to master
    - name: Doxygen
      working-directory: ${{github.workspace}}
      shell: bash
      run: doxygen
